# This is a basic workflow that is manually triggered

name: build-and-test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch, push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: build
      run: |
        gcc --version
        g++ -Wall -Wextra -Werror -std=c++23 -c -O2 -fconstexpr-ops-limit=100000000 great_indiction.cpp
        cd test
        g++ -std=c++23 -c catch_amalgamated.cpp
        g++ -Wall -Wextra -Werror -std=c++23 test01.cpp ../great_indiction.o ./catch_amalgamated.o -o test01

    - name: test
      run: |
        cd test
        ./test01
